apiVersion: v1
kind: Service
metadata:
  name: myshop-flask-service
spec:
  type: NodePort
  selector:
    app: myshop-flask-app
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30036
